CREATE TABLE cia_aberta_cad (
  AUDITOR varchar(100),
  BAIRRO varchar(100),
  BAIRRO_RESP varchar(100),
  CATEG_REG varchar(20),
  CD_CVM numeric(7, 0),
  CEP numeric(8, 0),
  CEP_RESP numeric(8, 0),
  CNPJ_AUDITOR varchar(20),
  CNPJ_CIA varchar(20),
  COMPL varchar(100),
  COMPL_RESP varchar(100),
  CONTROLE_ACIONARIO varchar(30),
  DDD_FAX varchar(4),
  DDD_FAX_RESP varchar(4),
  DDD_TEL varchar(4),
  DDD_TEL_RESP varchar(4),
  DENOM_COMERC varchar(100),
  DENOM_SOCIAL varchar(100),
  DT_CANCEL date,
  DT_CONST date,
  DT_INI_CATEG date,
  DT_INI_RESP date,
  DT_INI_SIT date,
  DT_INI_SIT_EMISSOR date,
  DT_REG date,
  EMAIL varchar(100),
  EMAIL_RESP varchar(100),
  FAX numeric(15, 0),
  FAX_RESP numeric(15, 0),
  LOGRADOURO varchar(100),
  LOGRADOURO_RESP varchar(100),
  MOTIVO_CANCEL varchar(80),
  MUN varchar(100),
  MUN_RESP varchar(100),
  PAIS varchar(100),
  PAIS_RESP varchar(100),
  RESP varchar(100),
  SETOR_ATIV varchar(100),
  SIT varchar(40),
  SIT_EMISSOR char(80),
  TEL numeric(15, 0),
  TEL_RESP numeric(15, 0),
  TP_ENDER char(30),
  TP_MERC varchar(50),
  TP_RESP varchar(100),
  UF char(2),
  UF_RESP char(2)
);
